name: multiple_images_picker

description: Flutter package that allows you to pick multiple images from your photo gallery on iOS and Android. It also allows you to access the camera and take photos within the application.
version: 1.1.0
homepage: https://github.com/loic-hamdi/multiple_images_picker

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.loichamdi.multipleimagespicker
        pluginClass: MultipleImagesPickerPlugin
      ios:
        pluginClass: MultipleImagesPickerPlugin

environment:
  sdk: '>=3.2.0'
  flutter: ">=3.16.0"
